services:
  pinarakcoffe:
    depends_on:
      - db
    build: .
    container_name: pinarakcoffe
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=pinarakcoffe
    networks:
      - pinarakcoffe-network

  db:
    image: mysql:8.0
    container_name: pinarakcoffe-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pinarakcoffe
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - pinarakcoffe-network

networks:
  pinarakcoffe-network:
    driver: bridge

volumes:
  db_data:
